# language
language: node_js

# node versions
node_js:
  - "0.12"

# branches
branches:
  only:
    - master

# variables
env:
  global:
    secure: IA4sLshYz/EVZevKlLOQXyfZHgkCZJC6Tnz22Wt6rCJ8QhfCYOY8kla5ZnBKz2Tah/8qGLp2fPSZey0qAYLg0Buz2CxZmUJ5GQeEAnhePnDYr5UHkmZPYhKiabOsexqQsjDcUwRZ4tN6TZ/XY0aVyyQWOaJ+zqoF25WzKTC+h3a2MQYTWsH1VSfPojR3Glb/aqqjQTQtpFuchp4bftXoVmge5zHjo3kJ4ZH2O7lipg6bOMGmOwvZPSYn01hxduR9svL0cEKWgB3oUmC8PgaP0e5szLCq4shjRFMjyJcO+lEbQIoUa2Np1aKUddfFS/7nOBBnDVKJ3eOhbMIeQn7FMRpGG6hHigT/lsYSMvN7Y/0o/JulCWdRlSK45xbIJcJYK/EAxbqJPUCw4/ZyUbzCK1XZamwQZVeQPrb9f9AmSj6dFWLjlYi/h/k/qwRih3P2kmEueZYbkk5XjiarXQYKAuop2fp56y1sAybBwA714b0rwRDsRhHbr4d40lTq39uNh7HY2A66YVu6qGkgS5F1j8ImelLGlCrHjth5xmx/x/o9q37KhTuiNKxTKxSecr9yvmSCloSLkLNb/9vb+ORWgBSGmIe7nXyzxW8Dqdp2Mj4wnw9zShSq61t56pwKBAugSubhjiZ9tTQ3aCOmt8dLe2twCVFKSs//qnZVZu9NhD0=

# scripts
install: npm install
script: node build

# deployement
after_success:

  # configure
  - git config --global user.name "${GIT_NAME}"
  - git config --global user.email "${GIT_EMAIL}"
  - git remote add github "https://${GH_TOKEN}@github.com/chuckeles/hellcourtgame.com.git"

  # deploy to github
  - git subtree push --prefix build github gh-pages
